controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Appeal;
use app\models\Article;
use app\models\Client;
use app\models\Comments;
use app\models\Faq;
use app\models\InvestorContactForm;
use app\models\Myobject;
use app\models\MyobjectSearch;
use app\models\PhotoObject;
use app\models\Requests;
use app\models\RequestViewForm;
use app\models\Seo;
use app\models\Settings;
use app\models\Studio;
use app\models\Subscription;
use app\service\Notify;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => 'main-page'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $cache = Yii::$app->cache;
        if (!$settings = $cache->get('settings')) {
            $settings = Settings::find()->indexBy('key')->asArray()->all();
            $cache->set('settings', $settings, null);
        }
        Yii::$app->params['settings'] = $settings;
        $cacheSEO = Yii::$app->cache;
        if (!$settingsSEO = $cache->get('settingsSEO')) {
            $settingsSEO = Seo::find()->indexBy('id')->asArray()->all();
            $cacheSEO->set('settingsSEO', $settingsSEO, null);
        }
        Yii::$app->params['settingsSEO'] = $settingsSEO;
    }

    public function actionIndex()
    {
        $this->layout = 'main-index';
        $this->view->params['keywords'] =  Yii::$app->params['settingsSEO'][1]['SEO_KEY'];
        $this->view->params['title'] =  Yii::$app->params['settingsSEO'][1]['SEO_TITLE'];
        $this->view->params['description'] =  Yii::$app->params['settingsSEO'][1]['SEO_DESCRIPTION'];
        return $this->render('index');
    }

    public function actionObjects()
    {
        $this->view->params['keywords'] =  Yii::$app->params['settingsSEO'][2]['SEO_KEY'];
        $this->view->params['title'] =  Yii::$app->params['settingsSEO'][2]['SEO_TITLE'];
        $this->view->params['description'] =  Yii::$app->params['settingsSEO'][2]['SEO_DESCRIPTION'];
        $filter = Yii::$app->request->get();
        $query = Myobject::find()->joinWith('studio');
        if (count($filter)>0) {
            $query->andWhere(['>','studio.square',$filter['suare1']]);
            $query->andWhere(['<','studio.square',$filter['suare2']]);
            $query->andWhere(['>','studio.price',$filter['price1']]);
            $query->andWhere(['<','studio.price',$filter['price2']]);
        } else {
            $filter['suare1'] = 8;
            $filter['suare2'] = 40;
            $filter['price1'] = 1500000;
            $filter['price2'] = 120000000;
        }
        $query->andWhere(['object_type' => 0, 'show_in_site' => 1, 'deleted'=>0]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 12]);
        $objects = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        $studio = [];
        foreach ($objects as $object) {
            $studio[$object->id] = Myobject::getStudioCount($object->id);
        }
        return $this->render('objects', [
            'objects' => $objects,
            'pages' => $pages,
            'studio' => $studio,
            'filter' => $filter,

        ]);
    }

    public function actionObjectsFull($id)
    {

        $id = (int)$id;
        $model = new RequestViewForm();
        $object = Myobject::findOne($id);

        $this->view->params['keywords'] =  $object->SEO_KEY;
        $this->view->params['title'] =  $object->SEO_TITLE;
        $this->view->params['description'] =  $object->SEO_DESCRIPTION;

        $object_photo = PhotoObject::find()->where(['myobject_id' => $id, 'photo_type' => 0])->all();
        $studio = Studio::find()->where(['myobject_id' => $id])->all();
        $countStudio = Myobject::getStudioCount($id);
        if ($model->load(Yii::$app->request->post())) {
            $appeal = new Appeal();
            $appeal->phone = Yii::$app->request->post('RequestViewForm')['phone'];
            $appeal->type_appeal = 1;
            $appeal->save();
            Yii::$app->getSession()->setFlash('success', [
                'type' => 'success',
                'duration' => 6000,
                'icon' => 'fa fa-users',
                'message' => 'Заявка отправленна',
                'positonY' => 'top',
                'positonX' => 'center'
            ]);
            Notify::sendNotifyToAdmin('request_contacts','Новая запись на просмотр');
            return $this->refresh();
        }
        return $this->render('objects-full', [
            'object' => $object,
            'object_photo' => $object_photo,
            'model' => $model,
            'studio' => $studio,
            'countStudio' => $countStudio
        ]);
    }

    public function actionProjects()
    {
        $this->view->params['keywords'] =  Yii::$app->params['settingsSEO'][3]['SEO_KEY'];
        $this->view->params['title'] =  Yii::$app->params['settingsSEO'][3]['SEO_TITLE'];
        $this->view->params['description'] =  Yii::$app->params['settingsSEO'][3]['SEO_DESCRIPTION'];
        $query = Myobject::find()->where(['object_type' => 1, 'show_in_site' => 1,'deleted'=>0]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 12]);
        $objects = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        $studio = [];
        foreach ($objects as $object) {
            $studio[$object->id] = Myobject::getStudioCount($object->id);
        }
        return $this->render('projects', [
            'objects' => $objects,
            'pages' => $pages,
            'studio' => $studio,

        ]);
    }

    public function actionProjectsFull($id)
    {
        $id = (int)$id;
        $model = new RequestViewForm();
        $object = Myobject::findOne($id);

        $this->view->params['keywords'] =  $object->SEO_KEY;
        $this->view->params['title'] =  $object->SEO_TITLE;
        $this->view->params['description'] =  $object->SEO_DESCRIPTION;

        $object_photo = PhotoObject::find()->where(['myobject_id' => $id, 'photo_type' => 1])->all();
        $studio = Studio::find()->where(['myobject_id' => $id])->all();
        return $this->render('projects-full', [
            'object' => $object,
            'object_photo' => $object_photo,
            'model' => $model,
            'studio' => $studio
        ]);
    }

    public function actionArticles($category = null)
    {
        $this->layout = 'main-page';
        $this->view->params['keywords'] =  Yii::$app->params['settingsSEO'][4]['SEO_KEY'];
        $this->view->params['title'] =  Yii::$app->params['settingsSEO'][4]['SEO_TITLE'];
        $this->view->params['description'] =  Yii::$app->params['settingsSEO'][4]['SEO_DESCRIPTION'];
        $query = Article::find()->where(['deleted'=>0,])->orderBy(['id'=>SORT_DESC]);
        if ($category) {
            $query->andWhere(['category_id'=>$category]);
        }
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 12]);
        $articles = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('articles', [
            'articles' => $articles,
            'pages' => $pages,

        ]);
    }

    public function actionArticleFull($id)
    {
        $this->layout = 'main-page';
        $id = (int)$id;
        $model = new ContactForm();
        $article = Article::findOne($id);

        $this->view->params['keywords'] =  $article->SEO_KEY;
        $this->view->params['title'] =  $article->SEO_TITLE;
        $this->view->params['description'] =  $article->SEO_DESCRIPTION;

        $comments = Comments::find()->where(['post_id' => $id])->asArray()->all();
        $_comments = array();
        foreach ($comments as $comment) {
            $_comments[$comment['id']] = $comment;
        }
        $comments = build_tree($_comments);
        unset($_comments);
        $comments = getCommentsTemplate($comments);

        return $this->render('articles-full', [
            'article' => $article,
            'model' => $model,
            'comments' => $comments
        ]);
    }

    public function actionCreateComment($id) {
        $model = new ContactForm();
        $request = Yii::$app->request;

            if ($model->load($request->post())) {
                $comment = new Comments();
                $comment->post_id = $id;
                $comment->email = $model->email;
                $comment->author = $model->name;
                $comment->comment = $model->body;
                $comment->parent_id = $model->commentId;
                $comment->save();

views/site/_catalog-dark.php
<?php

use app\models\Instagram;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\MaskedInput;

$getCatalogForm = new \app\models\GetCatalogForm();
?>
<div id="catalog-fon">
    <div class="container">
        <div class="site-objects">
            <div id="object-call" class="pull-right">
                <div class="col-md-12">
                <h3><strong>Получите актуальный каталог свободных студий с вариантами отделки и персональнй подбор по
                        заданным критериям</strong></h3>
                <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                <br>
                </div>
                <?php $form = \kartik\form\ActiveForm::begin([
                    'method' => 'post',
                    'action' => Url::to(['site/get-catalog']),
                ]); ?>
                <div class="col-md-12" style="text-align: center">
                    <div class='has-feedback'>
                        <?= $form->field($getCatalogForm, 'phone')
                            ->widget(MaskedInput::className(),
                                [
                                    'mask' => '+7(999)999-99-99',
                                    'class' => 'form-control tel_input get-catalog-input',
                                    'clientOptions' => [
                                        'clearIncomplete' => true
                                    ],
                                    'options' => [
                                        'class' => 'form-control tel_input get-catalog-input',
                                        'placeholder' => 'Номер телефона',
                                    ],
                                ])->label(false);
                        ?>
                        <span style='font-size: 20px; top:8px'
                              class="glyphicon glyphicon-phone form-control-feedback"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <?= $form->field($getCatalogForm, 'captcha')->widget(\yii\captcha\Captcha::classname(), [
                        'options' => [
                            'class' => 'form-control tel_input get-catalog-input',

                        ],
                    ]) ?>
                </div>
                <div class="col-md-12">
                    <div class='iagree'>
                        <?= $form->field($getCatalogForm, 'agree')->checkbox(['class' => 'get-catalog-checkbox'])->label('<span>Я ознакомился с <a href=\'#\'> условиями обратотки данных и политикой конфиденциальности</a></span>') ?>
                    </div>
                </div>

                <div class="col-md-12" style="text-align: center">
                    <?= Html::submitButton('ПОЛУЧИТЬ КАТАЛОГ И КОНСУЛЬТАЦИЮ', ['class' => 'get-catalog-submit']) ?>
                </div>
                <?php $form::end() ?>

            </div>
        </div>
    </div>
</div>

views/site/_catalog.php
<?php

use app\models\Instagram;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\MaskedInput;

$getCatalogForm = new \app\models\GetCatalogForm();
?>
<div id="catalog-fon">
    <div class="container">
        <div class="site-objects">
            <div id="object-call" class="pull-right">
                <div class="col-md-12">
                <h3><strong>Получите актуальный каталог свободных студий с вариантами отделки и персональнй подбор по
                        заданным критериям</strong></h3>
                <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                <br>
                </div>
                <?php $form = \kartik\form\ActiveForm::begin([
                    'method' => 'post',
                    'action' => Url::to(['site/get-catalog']),
                ]); ?>
                <div class="col-md-12" style="text-align: center">
                    <div class='has-feedback'>
                        <?= $form->field($getCatalogForm, 'phone')
                            ->widget(MaskedInput::className(),
                                [
                                    'mask' => '+7(999)999-99-99',
                                    'class' => 'form-control tel_input get-catalog-input',
                                    'clientOptions' => [
                                        'clearIncomplete' => true
                                    ],
                                    'options' => [
                                        'class' => 'form-control tel_input get-catalog-input',
                                        'placeholder' => 'Номер телефона',
                                    ],
                                ])->label(false);
                        ?>
                        <span style='font-size: 20px; top:8px'
                              class="glyphicon glyphicon-phone form-control-feedback"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <?= $form->field($getCatalogForm, 'captcha')->widget(\yii\captcha\Captcha::classname(), [
                        'options' => [
                            'class' => 'form-control tel_input get-catalog-input',

                        ],
                    ]) ?>
                </div>
                <div class="col-md-12 ">
                    <div class='iagree'>
                        <?= $form->field($getCatalogForm, 'agree')->checkbox(['class' => 'get-catalog-checkbox'])->label('<span>Я ознакомился с <a href=\'#\'> условиями обратотки данных и политикой конфиденциальности</a></span>') ?>
                    </div>
                </div>

                <div class="col-md-12" style="text-align: center">
                    <?= Html::submitButton('ПОЛУЧИТЬ КАТАЛОГ И КОНСУЛЬТАЦИЮ', ['class' => 'get-catalog-submit']) ?>
                </div>
                <?php $form::end() ?>

            </div>
        </div>
    </div>
</div>

views/site/_comment.php
<?php

use app\models\Instagram;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\MaskedInput;

?>
<div class="contact-form">

    <h3>
        Оставить комментарий
    </h3>

    <?php $form = ActiveForm::begin() ?>
    <div class="row">
        <div class="col-md-6 has-feedback">
            <?= $form->field($model, 'name')->textInput(['placeholder' => 'Имя'])->label(false) ?>
            <?= Html::img('/img/contact-user-ico.png', ['class' => 'contact-form-ico']); ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'email')->textInput(['placeholder' => 'E-mail'])->label(false) ?>
            <?= Html::img('/img/contact-email-ico.png', ['class' => 'contact-form-ico']); ?>
        </div>
        <div class="col-md-12">
            <?= $form->field($model, 'body')->textarea(['placeholder' => 'Сообщение'])->label(false) ?>
            <?= Html::img('/img/contact-message-ico.png', ['class' => 'contact-form-ico']); ?>
        </div>
        <div class="col-md-12">
            <?= $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::classname(), [
                'template' => '<div class="col-xs-6" style="padding-left: 0px">{input}</div><div class="col-xs-6">{image}</div>',
                'options' => ['placeholder' => 'CAPTCHA Code', 'class' => 'form-control']
            ])->label(false) ?>
        </div>
        <div class="col-md-12" style="text-align: center">
            <br>
            <?= Html::submitButton('ОТПРАВИТЬ', ['class' => 'contact-form-submit']) ?>
        </div>
    </div>
    <?php $form::end() ?>
</div>

views/site/_instagram.php
<?php

use app\models\Instagram;
use yii\helpers\Html;

?>
<div id="site-instagram">
    <div class="container">
        <div class="site-objects">
            <div id="object-instagram" class="head1">
                <div class="row">
                    <div class="col-lg-6">
                        <span class="r-blue"> Instagram</span>
                        <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                    </div>
                    <div class="col-lg-6 pull-right">
                        <div class="post-nav pull-right">
                            <?= Html::img('/img/detail-ico.png'); ?>
                            <?=Html::a('  Все посты',['/'],['class'=>'post-nav-all'])?>
                                <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-left"></i></a>
                                <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-right"></i></a>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <?php
                    $d = new Instagram();
                    foreach ($d->getPost() as $post) {
                        echo '<div class="col-lg-3 col-md-4"><div class="object-item">';
                        echo Html::a(Html::img($post->images->standard_resolution->url,['class' => 'img-responsive img-rounded ']),$post->link);
                        echo Html::img('/img/inst-ico.png',['class'=>'instagram-ico']);
                        echo '</div></div>';
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>

views/site/_map-dark.php
<?php

use app\models\Myobject;
use yii\helpers\Html;

?>
<div id="map-fon">
    <div class="container">
        <div class="site-objects">
            <div id="object-map" class="head1">
                <span class="r-blue">Карта </span> <span class="r-brown"> Объектов</span>
                <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                <div id="map">

                </div>
            </div>
        </div>
    </div>
</div>

    <style>
        #map {
            width: 100%;
            height: 770px;
            padding: 0;
            margin: 0;
        }
    </style>
    <style>
        .YMaps-layer-container img {
            max-width: none;
        }
    </style>
<?php
$myObject = Myobject::getAllGeoObject();
$countObject = count($myObject);
$coordX = $myObject[0]['coord_x'];
$coordY = $myObject[0]['coord_y'];
$script = <<<JS
var myMap = null;
var objectCollection = null;
function addPlacemark (arr) {
    
    for (step=0;step<arr.length;step++) {
        var myPlacemark = new ymaps.Placemark([arr[step].coord_x,arr[step].coord_y], {
            hintContent: 'asdasdasd',
        },{
            iconLayout: 'default#image',
            iconImageHref: '/img/map-ico.png',
            iconImageSize: [30, 42],
            
        });
        objectCollection.add(myPlacemark);
        myMap.geoObjects.add(objectCollection);
    }
}       
ymaps.ready(function () {
    objectCollection = new ymaps.GeoObjectCollection();
    myMap = new ymaps.Map('map', {
        center: [$coordX,$coordY],
        zoom: 11,
    });
    $.get("/site/get-geo-object",{type:0},function (data) {
        addPlacemark(data);
    })
    myMap.behaviors.disable('scrollZoom');
    myMap.behaviors.disable('dblClickZoom');
});
JS;
$this->registerJsFile("https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=7c4fab10-b262-4dc9-b2d0-968fd789cb4a;", ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJs($script, yii\web\View::POS_READY);
?>

views/site/_news.php
<?php

use app\models\Article;
use app\models\Instagram;
use app\models\Myobject;
use yii\helpers\Html;

?>
<div id="site-block-news">
    <div class="container">
        <div class="site-objects">
            <div id="object-instagram" class="head1">
                <div class="row">
                    <div class="col-lg-6">
                        <span class="r-blue"> Последние </span> <span class="r-brown"> Новости</span> <br>
                        <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                    </div>
                    <div class="col-lg-6 pull-right">
                        <div class="post-nav pull-right">
                            <?= Html::img('/img/detail-ico.png'); ?>
                            <?=Html::a('  Все новости',['/site/articles'],['class'=>'post-nav-all'])?>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-left"></i></a>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-right"></i></a>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <?php
                    $objects = Article::find()->where(['deleted'=>0])->orderBy('id DESC')->limit(3)->all();
                    foreach ($objects as $article) { ?>
                        <div class="col-lg-4">
                            <div class="article-item">
                                <?= Html::a(Html::img($article->photo, ['class' => 'img-responsive img-rounded']),['/article-full','id'=>$article->id])?>
                                <div class="object-list-item">
                                    <div class="article-date"><?= date('M d, Y', $article['created_at']) ?></div>
                                    <div class="article-name">
                                        <?=Html::a($article->name,['/article-full','id'=>$article->id],['class'=>'object-detail'])?>
                                    </div>
                                    <div class="article-short_description"><?php
                                        $string = strip_tags($article->short_description);
                                        $string = substr($string, 0, 20);
                                        $string = rtrim($string, "!,.-");
                                        $string = substr($string, 0, strrpos($string, ' '));
                                        echo $string . "… ";
                                        ?></div>
                                    <div class="clearfix"></div>
                                    <div class="object-details r-blue"><?= Html::img('/img/detail-ico.png') ?>
                                            <?=Html::a('Подробнее',['/article-full','id'=>$article->id],['class'=>'object-detail'])?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php }?>
                </div>

            </div>
        </div>
    </div>

views/site/_object.php
<?php

use app\models\Instagram;
use app\models\Myobject;
use yii\helpers\Html;

?>
<div id="site-block-object">
    <div class="container">
        <div class="site-objects">
            <div id="object-instagram" class="head1">

                <div class="row">
                    <div class="col-lg-6">
                        <span class="r-blue"> Еще</span> <span class="r-brown"> Объекты</span>
                        <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                    </div>
                    <div class="col-lg-6 pull-right">
                        <div class="post-nav pull-right">
                            <?= Html::img('/img/detail-ico.png'); ?>
                            <?=Html::a('  Все oбъекты',['/site/objects'],['class'=>'post-nav-all'])?>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-left"></i></a>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-right"></i></a>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <?php
                    $objects = Myobject::find()->where(['object_type' => 0,'deleted'=>0])->limit(3)->all();
                    $studio = [];
                    foreach ($objects as $object) {
                        $studio[$object->id] = Myobject::getStudioCount($object->id);
                    }
                    foreach ($objects

                    as $object) { ?>
                    <div class="col-lg-4 col-md-4">
                        <div class="object-item">
                            <?= Html::a(Html::img($object->image, ['class' => 'img-responsive img-rounded']), ['/objects-full', 'id' => $object->id]) ?>
                            <div class="object-list-item">
                                <div class="object-metro r-blue">
                                    <?= Html::a('Метро:',[$object->metro]) ?></div>
                                <div class="object-short_description"><?php
                                    $string = strip_tags($object->short_description);
                                    $string = substr($string, 0, 160);
                                    $string = rtrim($string, "!,.-");
                                    $string = substr($string, 0, strrpos($string, ' '));
                                    echo $string . "… ";
                                    ?></div>
                                <div class="object-address">
                                    <?= Html::img('/img/address-ico.png') ?>
                                    <?= $object->address ?>
                                </div>
                                <div class="object-studio"><span class="pull-left">Студий: <?=$studio[$object->id]['payStudio']?>/<?=$studio[$object->id]['allStudio']?></span>
                                    <span class="pull-right r-brown font-weight-bold">от <?= number_format((int)$object->price, 0, '.', ' '); ?> руб</span>
                                </div>
                                <div class="clearfix"></div>
                                <div class="object-details r-blue"><?= Html::img('/img/detail-ico.png') ?>
                                    <?=Html::a('Подробнее',['/objects-full','id'=>$object->id],['class'=>'object-detail'])?>
                                </div>
                            </div>


                            <?php echo '</div></div>';
                            }
                            ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>

views/site/_project.php
<?php

use app\models\Instagram;
use app\models\Myobject;
use yii\helpers\Html;

?>
<div id="fon1">
    <div class="container">
        <div class="site-objects">
            <div id="object-instagram" class="head1">

                <div class="row">
                    <div class="col-lg-6">
                        <span class="r-blue"> Реализованные </span> <span class="r-brown"> Проекты</span>
                        <?= Html::img('/img/image-znak.png', ['class' => 'image-znak']); ?>
                    </div>
                    <div class="col-lg-6 pull-right">
                        <div class="post-nav pull-right">
                            <?= Html::img('/img/detail-ico.png'); ?>
                            <?=Html::a('  Все проекты',['/site/projects'],['class'=>'post-nav-all'])?>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-left"></i></a>
                            <a href="#" class="post-nav-ico"> <i class="fa fa-long-arrow-right"></i></a>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <?php
                    $objects = Myobject::find()->where(['object_type' => 1])->limit(3)->all();
                    foreach ($objects

                    as $object) { ?>
                    <div class="col-lg-4 col-md-4">
                        <div class="object-item">
                            <?= Html::img($object->image, ['class' => 'img-responsive img-rounded']) ?>
                            <div class="object-list-item">
                                <div class="object-metro r-blue">
                                    Метро: <?= $object->metro ?></div>
                                <div class="object-short_description"><?= $object->short_description ?></div>
                                <div class="object-details r-blue"><?= Html::img('/img/detail-ico.png') ?>
                                    <?=Html::a('Подробнее',['/projects-full','id'=>$object->id],['class'=>'object-detail'])?>
                                </div>
                            </div>


                        <?php echo '</div></div>';
                        }
                        ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <div class="container">
        <div class="site-objects">
            <div class="row" style="margin-bottom: 40px ">
                <div class="col-lg-6">
                    <div id="object-breadcrumbs">
                        <?= Html::a('Главная ', ['/']) ?> / <?= Html::a(' 404', ['/error']) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 error_404">404</div>
                <div class="col-md-6">
                    <p><span>К СОЖАЛЕНИЮ...</span> СТРАНИЦА НЕ НАЙДЕНА.</p>
                    <p>Страница которую ви ищите, не существует,<br> возможно она была перемещена или удалена</p>
                    <a href="/" class="site-error-back">Вернутся на главную</a>
                </div>
            </div>
        </div>
    </div>
</div>